"""agregando ruta de imagen

Revision ID: 635e6a873227
Revises: 4a32e71844d5
Create Date: 2026-06-05 12:54:52.325566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635e6a873227'
down_revision: Union[str, None] = '4a32e71844d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('image_filename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_filename')
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
