"""agregando campos a producto

Revision ID: ef13b0d8c245
Revises: 9de327aab61d
Create Date: 2026-06-07 20:09:33.026020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef13b0d8c245'
down_revision: Union[str, None] = '9de327aab61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('features', sa.String(length=2000), nullable=True))
    op.add_column('products', sa.Column('specs', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specs')
    op.drop_column('products', 'features')
    # ### end Alembic commands ###
